### PR TITLE
Sdp test

### PR DESCRIPTION
**Pull request by TianqiZhang**

### CODE REVIEW

**Comment by TianqiZhang** [comment]
Docs Build status updates of commit _[7d6aea7](https://github.com/TianqiZhang/ref102/pull/2/commits/7d6aea79cc26c629adfefbc494b7d972f7061aea)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-a8b5c94e)

<a id="a8b5c94e"></a>
###
 - **[Error]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/TianqiZhang/ref102, working directory: W:\lffb-s, target branch: master, target branch commit: 302105173e1dcdb66f2ea24f62185b69cb0abd14, source commit: 7d6aea79cc26c629adfefbc494b7d972f7061aea.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C5%5C14%5C995df681-e42a-acd0-12e7-b6061ee7e517%5CPullRequest%5C201905140522516771-2%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=UccYfuB5ayV8twcXUpOYRXYo76sdZXSpyLQSqPiOJeI%3D&st=2019-05-14T05%3A17%3A59Z&se=2019-06-14T05%3A22%3A59Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by TianqiZhang** [comment]
Docs Build status updates of commit _[dd488dd](https://github.com/TianqiZhang/ref102/pull/2/commits/dd488dd57a6bbaad3826f901b9a820394b7da36a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.openpublishing.publish.config.json](https://github.com/TianqiZhang/ref102/blob/sdpTest/.openpublishing.publish.config.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C5%5C14%5C995df681-e42a-acd0-12e7-b6061ee7e517%5CPullRequest%5C201905140523420695-2%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=j8jCwvfAzndi8uxOy31t%2FZpv51ECk2y8gluGnKfiHls%3D&st=2019-05-14T05%3A20%3A10Z&se=2019-06-14T05%3A25%3A10Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by TianqiZhang** [comment]
Docs Build status updates of commit _[e248eef](https://github.com/TianqiZhang/ref102/pull/2/commits/e248eef38db483f45383742c132f8d770901d3b1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.openpublishing.publish.config.json](https://github.com/TianqiZhang/ref102/blob/sdpTest/.openpublishing.publish.config.json) | :white_check_mark:Succeeded | |
[ref102/xml/index.xml](https://github.com/TianqiZhang/ref102/blob/sdpTest/ref102/xml/index.xml) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C5%5C20%5C995df681-e42a-acd0-12e7-b6061ee7e517%5CPullRequest%5C201905200724019848-2%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=pSip9DN8mFehWjhZRW3JC3yO5fqFqYxoY3CbqloFJK0%3D&st=2019-05-20T07%3A20%3A17Z&se=2019-06-20T07%3A25%3A17Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by TianqiZhang** [comment]
Docs Build status updates of commit _[fe2e1b7](https://github.com/TianqiZhang/ref102/pull/2/commits/fe2e1b7216d561b52da634b9e2a9afddda45e11d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[ref102/api/CatLibrary.Cat-2.Age.yml](https://github.com/TianqiZhang/ref102/blob/sdpTest/ref102/api/CatLibrary.Cat-2.Age.yml) | :warning:Warning | | [Details](#user-content-d115383d-397a6562)
[.openpublishing.publish.config.json](https://github.com/TianqiZhang/ref102/blob/sdpTest/.openpublishing.publish.config.json) | :white_check_mark:Succeeded | |
[ref102/xml/index.xml](https://github.com/TianqiZhang/ref102/blob/sdpTest/ref102/xml/index.xml) | :white_check_mark:Succeeded | |

<a id="d115383d-397a6562"></a>
### [ref102/api/CatLibrary.Cat-2.Age.yml](https://github.com/TianqiZhang/ref102/blob/sdpTest/ref102/api/CatLibrary.Cat-2.Age.yml)
 - **Line 1**: **[Warning]** `````Invalid file link:(~/api/cc3e540b-63b0-4edf-b0c0-69c38f3795d3).`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C5%5C22%5C995df681-e42a-acd0-12e7-b6061ee7e517%5CPullRequest%5C201905220444457367-2%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=0qzCCoOnqjI9z1kdZpeEl36glftG1A7LtTr%2Bd%2BBwiaI%3D&st=2019-05-22T04%3A41%3A20Z&se=2019-06-22T04%3A46%3A20Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by TianqiZhang** [comment]
Docs Build status updates of commit _[85f7f2d](https://github.com/TianqiZhang/ref102/pull/2/commits/85f7f2d49b5fac44452c11d0601dd10971cc96a0)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[ref102/api/CatLibrary.Cat-2.Age.yml](https://github.com/TianqiZhang/ref102/blob/sdpTest/ref102/api/CatLibrary.Cat-2.Age.yml) | :warning:Warning | | [Details](#user-content-d115383d-ba738531)
[.openpublishing.publish.config.json](https://github.com/TianqiZhang/ref102/blob/sdpTest/.openpublishing.publish.config.json) | :white_check_mark:Succeeded | |
[ref102/xml/index.xml](https://github.com/TianqiZhang/ref102/blob/sdpTest/ref102/xml/index.xml) | :white_check_mark:Succeeded | |

<a id="d115383d-ba738531"></a>
### [ref102/api/CatLibrary.Cat-2.Age.yml](https://github.com/TianqiZhang/ref102/blob/sdpTest/ref102/api/CatLibrary.Cat-2.Age.yml)
 - **Line 1**: **[Warning]** `````Invalid file link:(~/api/cc3e540b-63b0-4edf-b0c0-69c38f3795d3).`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C6%5C13%5C995df681-e42a-acd0-12e7-b6061ee7e517%5CPullRequest%5C201906130733572815-2%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=wjYixA5Gkpt7RzChXPCXt2wn0w71MCocUfZu%2FGU55Vw%3D&st=2019-06-13T07%3A30%3A23Z&se=2019-07-14T07%3A35%3A23Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by yishengjin1413** [comment]
@TianqiZhang @TianqiZhang

**Comment by yishengjin1413** [comment]
@TianqiZhang

**Comment by TianqiZhang** [comment]
Docs Build status updates of commit _[9d0d826](https://github.com/TianqiZhang/ref102/commits/9d0d8266015114dbf2a31de2d0f54e020a6a487d)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-c3ca16ed)

<a id="c3ca16ed"></a>
###
 - **[Error]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/TianqiZhang/ref102, working directory: W:\oltb-s, target branch: HEAD, target branch commit: 3eb6a6355dfbc708ebe437908751a0500d5eedca, source commit: 9d0d8266015114dbf2a31de2d0f54e020a6a487d.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C8%5C9%5C995df681-e42a-acd0-12e7-b6061ee7e517%5CPullRequest%5C201908090706401783-2%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=w583RG2P5Uvjdc1VBkPQs1w8srfdyHi9oz7xR4CZvsE%3D&st=2019-08-09T07%3A01%3A50Z&se=2019-09-09T07%3A06%3A50Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by TianqiZhang** [comment]
Docs Build status updates of commit _[9d0d826](https://github.com/TianqiZhang/ref102/commits/9d0d8266015114dbf2a31de2d0f54e020a6a487d)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-a5f43917)

<a id="a5f43917"></a>
###
 - **[Error]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/TianqiZhang/ref102, working directory: W:\5yw1-s, target branch: HEAD, target branch commit: 3aaba0e145ac7a41d128da05493010f1eb69604b, source commit: 9d0d8266015114dbf2a31de2d0f54e020a6a487d.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C11%5C11%5C995df681-e42a-acd0-12e7-b6061ee7e517%5CPullRequest%5C201911110146102856-2%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ODnfg9EWR4BHKqGAhAq64S6jz0td6DlUi7ZF4aEQewI%3D&st=2019-11-11T01%3A41%3A19Z&se=2019-12-12T01%3A46%3A19Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by TianqiZhang** [comment]
Docs Build status updates of commit _[9e56ced](https://github.com/TianqiZhang/ref102/commits/9e56cedf99a17a58be8d05856ac00761812780ec)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.openpublishing.publish.config.json](https://github.com/TianqiZhang/ref102/blob/sdpTest/.openpublishing.publish.config.json) | :x:Error | | [Details](#user-content-d902ab53-956f3da7)
[]() | :x:Error | | [Details](#user-content-956f3da7)
[_dependentPackages/ECMA2Yaml/tools/Run.ps1](https://github.com/TianqiZhang/ref102/blob/sdpTest/_dependentPackages/ECMA2Yaml/tools/Run.ps1) | :x:Error | | [Details](#user-content-bd18f9f4-956f3da7)

<a id="d902ab53-956f3da7"></a>
### [.openpublishing.publish.config.json](https://github.com/TianqiZhang/ref102/blob/sdpTest/.openpublishing.publish.config.json)
 - **Line 80**: **[Error]** `````Failed to execute customized script at step docset_prebuild in docset ref102. Please check your .openpublishing.publish.config.json?on the configuration of the plug-ins for docset ref102 step docset_prebuild or ask for help?in Docs Support teams channel. Please also include the build report and the following error code for our team to troubleshoot: 1`````

<a id="956f3da7"></a>
###
 - **[Error]** `````Failed to load 1 files, aborting...`````
 - **Line 138**: **[Error]** `````W:\5b02-s\.optemp\packages\opbuild.scripts.1.81.1\tools\opbuild\docset.prebuild.ps1 failed to execute`````

<a id="bd18f9f4-956f3da7"></a>
### [_dependentPackages/ECMA2Yaml/tools/Run.ps1](https://github.com/TianqiZhang/ref102/blob/sdpTest/_dependentPackages/ECMA2Yaml/tools/Run.ps1)
 - **Line 82**: **[Error]** `````Error happened when executing plug-in script _dependentPackages/ECMA2Yaml/tools/Run.ps1 at step docset_prebuild. Please check your .openpublishing.publish.config.json?on the configuration of the plug-ins or ask for help?in Docs Support teams channel. Exit code: -1`````
 - **Line 217**: **[Error]** `````Error happened when executing plug-in script _dependentPackages/ECMA2Yaml/tools/Run.ps1 at step docset_prebuild. Please check your .openpublishing.publish.config.json?on the configuration of the plug-ins or ask for help?in Docs Support teams channel. Please also include the build report and the following error code for our team to troubleshoot: 1`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C11%5C11%5C995df681-e42a-acd0-12e7-b6061ee7e517%5CPullRequest%5C201911110146563283-2%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=QFNXV0ye%2FXW4xg%2BTlXwnzTtKiTln3tE4YVdHCn%2BXqTY%3D&st=2019-11-11T01%3A42%3A52Z&se=2019-12-12T01%3A47%3A52Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
